name: stemVAE
channels:
  - defaults
  - nvidia
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pip:
    - absl-py==1.4.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - anndata==0.8.0
    - annotated-types==0.5.0
    - anyio==3.7.1
    - argon2-cffi-bindings==21.2.0
    - argon2-cffi==21.3.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - attrs==23.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - bleach==6.0.0
    - blis==0.7.10
    - boltons==23.0.0
    - brotlipy==0.7.0
    - cachetools==5.3.1
    - catalogue==2.0.9
    - certifi==2022.12.7
    - cffi==1.15.1
    - charset-normalizer==2.0.4
    - click==8.1.7
    - cmake==3.26.4
    - comet-ml==3.33.8
    - comm==0.1.3
    - conda-content-trust==0.1.3
    - conda-package-handling==2.0.2
    - conda-package-streaming==0.7.0
    - conda==23.1.0
    - confection==0.1.1
    - configobj==5.0.8
    - contourpy==1.1.0
    - cryptography==38.0.4
    - cycler==0.11.0
    - cymem==2.0.7
    - debugpy==1.6.7
    - decorator==5.1.1
    - decoupler==1.4.0
    - defusedxml==0.7.1
    - docrep==0.3.2
    - docutils==0.20.1
    - dulwich==0.21.5
    - everett==3.1.0
    - exceptiongroup==1.1.2
    - executing==1.2.0
    - fastai==2.7.12
    - fastcore==1.5.29
    - fastdownload==0.0.7
    - fastjsonschema==2.17.1
    - fastprogress==1.0.3
    - feather-format==0.4.1
    - filelock==3.12.2
    - flatbuffers==23.5.26
    - fonttools==4.41.0
    - fqdn==1.5.1
    - frozenlist==1.4.0
    - fsspec==2023.6.0
    - future==0.18.3
    - galaxy-tool-util==23.0.4
    - galaxy-util==23.0.4
    - galaxyxml==0.4.14
    - gast==0.4.0
    - google-auth-oauthlib==1.0.0
    - google-auth==2.22.0
    - google-pasta==0.2.0
    - grpcio==1.56.0
    - gxargparse==0.2.5
    - h5py==3.9.0
    - idna==3.4
    - importlib-resources==6.0.0
    - inflect==7.0.0
    - iniconfig==2.0.0
    - ipykernel==6.24.0
    - ipython-genutils==0.2.0
    - ipython==8.14.0
    - ipywidgets==8.0.7
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.3.1
    - joypy==0.2.6
    - jsonpointer==2.4
    - jsonschema-specifications==2023.6.1
    - jsonschema==4.18.3
    - jupyter-client==8.3.0
    - jupyter-console==6.6.3
    - jupyter-core==5.3.1
    - jupyter-events==0.6.3
    - jupyter-server-terminals==0.4.4
    - jupyter-server==2.7.0
    - jupyter==1.0.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.8
    - keras==2.13.1
    - kiwisolver==1.4.4
    - langcodes==3.3.0
    - libclang==16.0.6
    - lightning-utilities==0.9.0
    - lit==16.0.6
    - llvmlite==0.40.1
    - lxml==4.9.3
    - markdown-it-py==3.0.0
    - markdown==3.4.3
    - markupsafe==2.1.3
    - matplotlib-inline==0.1.6
    - matplotlib==3.7.2
    - mdurl==0.1.2
    - mistune==3.0.1
    - mpmath==1.3.0
    - multidict==6.0.4
    - murmurhash==1.0.9
    - natsort==8.4.0
    - nbclassic==1.0.0
    - nbclient==0.8.0
    - nbconvert==7.7.1
    - nbformat==5.9.1
    - nest-asyncio==1.5.6
    - networkx==3.1
    - notebook-shim==0.2.3
    - notebook==6.5.4
    - numba==0.57.1
    - numpy==1.24.3
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-ml-py==11.525.131
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - nvitop==0.2.5.1
    - oauthlib==3.2.2
    - omnipath==1.0.7
    - opt-einsum==3.3.0
    - overrides==7.3.1
    - packaging==21.3
    - pandas==2.0.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathy==0.10.2
    - patsy==0.5.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==10.0.0
    - pip==22.3.1
    - platformdirs==3.9.1
    - pluggy==1.0.0
    - preshed==3.0.8
    - prometheus-client==0.17.1
    - prompt-toolkit==3.0.39
    - protobuf==3.20.3
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==13.0.0
    - pyasn1-modules==0.3.0
    - pyasn1==0.5.0
    - pycosat==0.6.4
    - pycparser==2.21
    - pydantic-core==2.3.0
    - pydantic==1.10.11
    - pygments==2.16.1
    - pyhsiclasso==1.4.2
    - pynndescent==0.5.10
    - pynvml==11.5.0
    - pyopenssl==22.0.0
    - pyparsing==3.0.9
    - pyreadr==0.4.7
    - pyro-api==0.1.2
    - pyro-ppl==1.8.5
    - pysocks==1.7.1
    - pytest==7.4.0
    - python-box==6.1.0
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytorch-lightning==2.0.4
    - pytz==2023.3
    - pyyaml==6.0.1
    - pyzmq==25.1.0
    - qtconsole==5.4.3
    - qtpy==2.3.1
    - referencing==0.29.1
    - repoze.lru==0.7
    - requests-oauthlib==1.3.1
    - requests-toolbelt==1.0.0
    - requests==2.28.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.5.2
    - routes==2.5.1
    - rpds-py==0.8.11
    - rpy2==3.5.14
    - rsa==4.9
    - ruamel.yaml.clib==0.2.6
    - ruamel.yaml==0.17.21
    - scanpy==1.9.3
    - scikit-learn==1.3.0
    - scikit-misc==0.3.0
    - scipy==1.10.1
    - seaborn==0.12.2
    - semantic-version==2.10.0
    - send2trash==1.8.2
    - sentry-sdk==1.29.2
    - session-info==1.0.0
    - setuptools==65.6.3
    - simplejson==3.19.1
    - six==1.16.0
    - smart-open==6.3.0
    - sniffio==1.3.0
    - sortedcontainers==2.4.0
    - soupsieve==2.4.1
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.4
    - spacy==3.6.1
    - srsly==2.4.7
    - stack-data==0.6.2
    - statsmodels==0.14.0
    - stdlib-list==0.9.0
    - sympy==1.12
    - tbb==2021.10.0
    - tensorboard-data-server==0.7.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboard==2.13.0
    - tensorboardx==2.6
    - tensorflow-estimator==2.13.0
    - tensorflow-io-gcs-filesystem==0.33.0
    - tensorflow==2.13.0
    - termcolor==2.3.0
    - terminado==0.17.1
    - thinc==8.1.12
    - threadpoolctl==3.2.0
    - tinycss2==1.2.1
    - tomli==2.0.1
    - toolz==0.12.0
    - torch==2.0.1
    - torchaudio==2.0.2
    - torchmetrics==1.0.1
    - torchvision==0.15.2
    - tornado==6.3.2
    - tqdm==4.64.1
    - traitlets==5.9.0
    - triton==2.0.0
    - typer==0.9.0
    - typing-extensions==4.5.0
    - tzdata==2023.3
    - tzlocal==5.0.1
    - umap-learn==0.5.4
    - uri-template==1.3.0
    - urllib3==1.26.14
    - wasabi==1.1.2
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.3.3
    - werkzeug==2.3.6
    - wheel==0.37.1
    - widgetsnbextension==4.0.8
    - wrapt==1.15.0
    - wurlitzer==3.0.3
    - yarl==1.9.2
    - zipstream-new==1.1.8
    - zstandard==0.18.0